image: python:latest

variables:
  CARDID: ""
  PASSWORD: ""
  SERVERCHANSCKEY: ""
  OPENID: ""
  PPTOKEN: ""
  PPTOPIC: ""
  TGBOTTOKEN: ""
  TGCHATID: ""
  SUBSINFO: ""
  DELAYS: ""
  GPATOKEN: ""

stages:
  - wait
  - run
  - retry

wait:
  stage: wait
  script:
    - sleep $DELAYS
  rules:
    - if: $DELAYS != ""

star:
  stage: run
  script:
    - 'curl --request POST
      --header "PRIVATE-TOKEN: $GPATOKEN"
      "https://gitlab.com/api/v4/projects/25111961/star"'
  rules:
    - if: $GPATOKEN != ""

run:
  stage: run
  script:
    - python -V  # Print out python version for debugging
    - python -m pip install --upgrade pip
    - pip install -r requirements-run.txt
    - echo "---Auto COVID Health Report---";
      if python LZU-Auto-COVID-Health-Report.py >> information.txt && cat information.txt; then
      echo "---Notify Success---";
      python Notify-Result.py success; else
      echo "---Error logging and Notifying---";
      python Notify-Result.py failure && cat information.txt;
      exit 1; fi

retry:
  stage: retry
  script:
    - 'curl --request POST
      --form token=$GPATOKEN
      --form ref=main
      --form "variables[DELAYS]=30m"
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"'
  rules:
    - if: $GPATOKEN != ""
      when: on_failure
