# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SERVERCHANSCKEY: ""
  OPENID: ""
  PPTOKEN: ""
  PPTOPIC: ""
  TGBOTTOKEN: ""
  TGCHATID: ""
  SUBSINFO: ""

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip
  - pip install -r requirements-run.txt

run:
  script:
    - python LZU-Auto-COVID-Health-Report.py >> information.txt
    - cat information.txt
    - python Notify-Result.py success ${CI_REPOSITORY_URL%.git}/-/pipelines/${CI_PIPELINE_ID}/builds

error_logging:
  script:
    - python Notify-Result.py failure ${CI_REPOSITORY_URL%.git}/-/pipelines/${CI_PIPELINE_ID}/builds
    - cat information.txt
  when: on_failure

