# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SERVERCHANSCKEY: ""
  OPENID: ""
  PPTOKEN: ""
  PPTOPIC: ""
  TGBOTTOKEN: ""
  TGCHATID: ""
  SUBSINFO: ""
  DELAYS: ""
  GPATOKEN: ""

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python -m pip install --upgrade pip
  - pip install -r requirements-run.txt

stages:
  - star
  - wait
  - run
  - error
  - retry

star:
  stage: star
  script:
    - curl --request POST --header "PRIVATE-TOKEN: $GPATOKEN" "https://gitlab.com/api/v4/projects/25111961/star"
  rules:
    - if: $GPATOKEN != ""

wait:
  stage: wait
  script:
    - sleep $DELAYS
  rules:
    - if: $DELAYS != ""

run:
  stage: run
  script:
    - python LZU-Auto-COVID-Health-Report.py >> information.txt
    - cat information.txt
    - python Notify-Result.py success $CI_JOB_URL

error:
  stage: error
  script:
    - cat information.txt
    - python Notify-Result.py failure $CI_PIPELINE_URL
  when: on_failure

retry:
  stage: retry
  script:
    - curl --request POST \
      --form token=$GPATOKEN \
      --form ref=main \
      --form "variables[DELAYS]=30m" \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"
  rules:
    - if: $GPATOKEN != ""
      when: on_failure
