name: 'Docker Version - GitHub Actions LZU Auto COVID Health Report'
    
on:
  workflow_dispatch:  # Allow manual triggers
    inputs:
      delays:
        description: 'Delayed time (Optional) 可选延迟时间'
        required: false
# schedule:
#   - cron: '0 23 * 1,2,7,8 *' # Schedule on CST 7 everyday during Jan. Feb. Jul. Aug.

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: Star original repository if GPATOKEN set
          run: |
            curl \
            -X PUT \
            -H 'authorization: token ${{ secrets.GPATOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            $GITHUB_API_URL/user/starred/HollowMan6/LZU-Auto-COVID-Health-Report
        - name: Auto COVID Health Report
          uses: HollowMan6/LZU-Auto-COVID-Health-Report@main
          with:
            CARDID: ${{ secrets.CARDID }}
            PASSWORD: ${{ secrets.PASSWORD }}
            DELAYS: ${{ github.event.inputs.delays }}
            SERVERCHANSCKEY: ${{ secrets.SERVERCHANSCKEY }}
            OPENID: ${{ secrets.OPENID }}
            PPTOKEN: ${{ secrets.PPTOKEN }}
            PPTOPIC: ${{ secrets.PPTOPIC }}
            TGBOTTOKEN: ${{ secrets.TGBOTTOKEN }}
            TGCHATID: ${{ secrets.TGCHATID }}
        - name: 'Re-run workflow if failed and GPATOKEN set'
          if: ${{ failure() }}
          run: |
            workflow_url=`curl $GITHUB_API_URL/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | grep workflow_url | cut -d \" -f 4` \
            && curl \
            -X POST \
            -H 'authorization: token ${{ secrets.GPATOKEN }}' \
            -H "Accept: application/vnd.github.v3+json" \
            $workflow_url/dispatches \
            -d '{"ref":"${{ github.ref }}", "inputs": { "delays": "30m" }}'
        - name: 'Web Push Notification if Success'
          env:
            SUBSINFO: ${{ secrets.SUBSINFO }}
          if: ${{ success() && (env.SUBSINFO != '') }}
          run: |
            job_url=`curl $GITHUB_API_URL/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | grep html_url | cut -d \" -f 4` \
            && pip install pywebpush six \
            && wget https://github.com/${{ github.repository }}/raw/main/webpush.py \
            && python webpush.py 成功 ${job_url}?check_suite_focus=true
        - name: 'Web Push Notification if Failed'
          env:
            SUBSINFO: ${{ secrets.SUBSINFO }}
          if: ${{ failure() && (env.SUBSINFO != '') }}
          run: |
            job_url=`curl $GITHUB_API_URL/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | grep html_url | cut -d \" -f 4` \
            && pip install pywebpush six \
            && wget https://github.com/${{ github.repository }}/raw/main/webpush.py \
            && python webpush.py 失败 ${job_url}?check_suite_focus=true